### ISSUE TITLE
Use GraphQL variables

### ISSUE THREAD

**Issue by mktcode** [Octobay/api#1]
Currently some variable query parameters are passed in directly in the template string. It's recommended to use GraphQL variables for this.

See: https://github.com/OctoBay/adapters/blob/main/githubUser.js#L12

**Comment by alo9507** [comment]
I'll take this one.

**Comment by mktcode** [comment]
I'll assign the other related issue to you as well then. :zany_face:

**Comment by alo9507** [comment]
I think this can be closed. Forgot to link the issue. Pretty ironic given the platform we're building 😅
